#!/usr/bin/env bash

set -e

cd $(git root)

# Create file list
list=""
IFS_BACKUP=$IFS
IFS=$'\n'
for file in $(git ls-files -m -o --exclude-standard)
do
	list="$list, \"$(basename $file)\""
done
IFS="$IFS_BACKUP"
list=${list#, }
msg="update $list"

# Truncate
if [[ ${#msg} -gt 80 ]]
then
	msg=$(echo $msg | cut -c -77)
	msg="$msg..."
fi

# Execute
TEMP="$*"
msg=${TEMP:-msg}

git add -A
git commit -m "\"$msg\""
