#!/usr/bin/env bash

set -eu

current=$(git branch --show-current)
if [ -z "$current" ]; then
	echo "[Error] You are currently not on a branch. Aborting..."
	exit 1
fi

git push --set-upstream origin $current
