#!/usr/bin/env bash

if [ -n "${GIT_AUTHOR_EMAIL+set}" ] && [ -n "${GIT_AUTHOR_NAME+set}" ] && [ -n "${GIT_COMMITTER_EMAIL+set}" ]
then
	echo $GIT_AUTHOR_NAME
	echo $GIT_AUTHOR_EMAIL
else
	git config user.name
	git config user.email
fi
