#!/usr/bin/env bash

searchRoot=${1:-.}

function visit
{
	dir=$1
	
	if [ -d "$dir/.git" ]
	then
		realpath "$dir" --relative-to "$PWD"
		return 0
	fi

	for x in $dir/*
	do
	    if [ -d "$x" ]
	    then
	    	visit "$x"
	    fi
	done
}

visit "$searchRoot"
