#!/usr/bin/env bash

ID=$1
# Compute prefix
if [ -z "$ID" ]
then
	TAG_PREFIX=""
else
	TAG_PREFIX="$ID/"
fi
# Read tags
VERSION=$(git tag --list "${TAG_PREFIX}v*" --sort=-v:refname | head -n 1)

STRIPPED="${VERSION%-pre.[0-9]*}"

if [ $(git tag -l "$STRIPPED") ]; then
	echo "$STRIPPED"
elif [ -n "$VERSION" ]; then
	echo "$VERSION"
fi

exit 1
