#!/usr/bin/env bash

set -e
shopt -s extglob

remote=${1}
reposDir="${XDG_REPOS_DIR:-$HOME/repos}"

path=$(git ls-remote --get-url ${remote})
path=$(echo $path | sed 's_git@\([0-9a-zA-Z.]*\):_\1/_g')
path=$(echo $path | sed 's_https://\([0-9a-zA-Z.]*\)/_\1/_g')
path="${path%.git}"
path=$reposDir/$path

git clone $remote $path

GREEN='\033[0;32m'
NC='\033[0m'
echo -e "$GREEN$path$NC"
