#!/usr/bin/env bash

channel="${1}"
if [ -z "$channel" ]
then
	echo "Usage: git produce <channel>"
	exit 1
fi

set -eu
remote="origin"
master="master"

function update
{
	git fetch $remote $channel 2> /dev/null || true
}

function checkout
{
	echo "[INFO] Attempting to reuse local production branch..."
	git checkout $channel 2> /dev/null || return -1
	echo "[INFO] Updating local production branch..."
	git merge --ff-only 2> /dev/null || true
}

function create
{
	echo "[INFO] Creating local production branch..."
	git checkout -B $channel $master
}

echo "[INFO] Fetching origin..."
update
checkout || create
echo "[INFO] Merging changes from $master..."
git merge $master --ff
echo "[INFO] Pushing changes to $remote..."
git push --set-upstream $remote $channel
echo "[INFO] Cleaning up..."
git checkout $master
