#!/usr/bin/env bash

set -e
shopt -s extglob

REMOTE=$1
REPOS_DIR="${XDG_REPOS_DIR:-$HOME/repos}"
INDEX_PATH="$REPOS_DIR/.git-deposit"

# Begin program
REPO_PATH=$(git ls-remote --get-url $REMOTE)
REPO_PATH=$(echo $REPO_PATH | sed 's_git@\([0-9a-zA-Z.]*\):_\1/_g')
REPO_PATH=$(echo $REPO_PATH | sed 's_https://\([0-9a-zA-Z.]*\)/_\1/_g')
REPO_PATH=${REPO_PATH%.git}
REPO_PATH=$REPOS_DIR/$REPO_PATH

git clone $REMOTE $REPO_PATH
echo $REPO_PATH > $INDEX_PATH

# Output
GREEN='\033[0;32m'
NC='\033[0m'
echo -e "$GREEN$REPO_PATH$NC"
