#!/usr/bin/env bash

if [ -n "${GIT_AUTHOR_EMAIL+set}" ] && [ -n "${GIT_AUTHOR_NAME+set}" ] && [ -n "${GIT_COMMITTER_EMAIL+set}" ]
then
	name=$GIT_AUTHOR_NAME
	email=$GIT_AUTHOR_EMAIL
else
	name=$(git config user.name)
	email=$(git config user.email)
fi

echo "$name <$email>"
