#!/usr/bin/env bash

set -e

# Create file list
list=""
for file in $(git ls-files -m -o --exclude-standard)
{
	list="$list, $(basename $file)"
}
list=${list#, }
echo $list
msg="update $list"

# Truncate
if [[ ${#msg} -gt 80 ]]
then
	msg=$(echo $msg | cut -c -77)
	msg="$msg..."
fi

# Execute
msg="${1:-$msg}"

git add -A
git commit -m "$msg"
