#!/usr/bin/env bash

set -e

HTTP_MODE=true

while test $# -gt 0
do
	case "$1" in
		--ssh)
				HTTP_MODE=false
				;;
		--http)
				HTTP_MODE=true
				;;
		--*)
				echo "Unknown option $1"
				exit 1
				;;
		*)
				;;
	esac
	shift
done

if $(git is)
then
	url=$(git ls-remote --get-url origin)
	url="${url%.git}"
else
	url="$(pwd)"
	url="${url/*\/repos\//}"
	url="https://${url}"
fi

if $HTTP_MODE
then
	url=$(echo $url | sed 's_git@\([0-9a-zA-Z.]+\):_https://\1/_g')
else
	url=$(echo $url | sed 's_https://\([0-9a-zA-Z.]+\)/_git@\1:_g')
fi

echo $url
