#!/usr/bin/env bash

set -eu

# Begin script
oldHead=$(git branch --show-current)

git fetch --prune origin master:master
git switch master
git feature prune

git switch $oldHead 2> /dev/null || true
