#!/usr/bin/env bash

PREFIX=""
SUFFIX=""

function append
{
	if [ -z "$SUFFIX" ]
	then
		SUFFIX="$@"
	else
		SUFFIX="$SUFFIX $@"
	fi
}
function prepend
{
	if [ -z "$PREFIX" ]
	then
		PREFIX="$@"
	else
		PREFIX="$PREFIX $@"
	fi
}

COUNT=$1
shift

for TOKEN in "$@"; do
	case $TOKEN in
		--)
			;;
		*)
			if [ "$COUNT" -gt 0 ]; then
				prepend $TOKEN
				((COUNT -= 1))
			else
				append $TOKEN
			fi
			;;
	esac
done

echo "$PREFIX \"$SUFFIX\""
